// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2LlXL_qLZkey4iRmRsd4xPoCIAIod8Bg',
    appId: '1:695952533978:web:dd9f73f60bdf6c67a138e3',
    messagingSenderId: '695952533978',
    projectId: 'gizmogate-97717',
    authDomain: 'gizmogate-97717.firebaseapp.com',
    storageBucket: 'gizmogate-97717.firebasestorage.app',
    measurementId: 'G-D1TZ00CDKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBBxa5W1FVcs2CLa-D3To7hCaXXFp46c',
    appId: '1:695952533978:android:b7b86390a6325988a138e3',
    messagingSenderId: '695952533978',
    projectId: 'gizmogate-97717',
    storageBucket: 'gizmogate-97717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_W1yiMou_j_ZGkppId9kjXuzgCVfzmgs',
    appId: '1:695952533978:ios:145f47719d47425fa138e3',
    messagingSenderId: '695952533978',
    projectId: 'gizmogate-97717',
    storageBucket: 'gizmogate-97717.firebasestorage.app',
    iosBundleId: 'com.example.gizmogate',
  );
}
